/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include"FreeRTOS.h"
#include"FreeRTOSConfig.h"
#include"task.h"
#include"led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void vMainAperiodicTaskFunction1(void *pvParam)
{
	while(1)
	{
		// work
		led_toggle(LED_RED);
		vTaskDelay(1000 / portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}

void vMainAperiodicTaskFunction2(void *pvParam)
{
	while(1)
	{
		// work
		led_toggle(LED_GREEN);
		vTaskDelay(1200 / portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}
void vMainAperiodicTaskFunction3(void *pvParam)
{
	while(1)
	{
		// work
		led_toggle(LED_BLUE);
		vTaskDelay(1650 / portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}
void vMainAperiodicTaskFunction4(void *pvParam)
{
	while(1)
	{
		// work
		led_toggle(LED_ORANGE);
		vTaskDelay(2000 / portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}
int main(void)
{
	led_init(LED_RED);
	led_init(LED_GREEN);
	led_init(LED_BLUE);
	led_init(LED_ORANGE);
	xTaskCreate(vMainAperiodicTaskFunction1, "APeriodic", configMINIMAL_STACK_SIZE, NULL, 4, NULL);
	xTaskCreate(vMainAperiodicTaskFunction2, "APeriodic", configMINIMAL_STACK_SIZE, NULL, 4, NULL);
	xTaskCreate(vMainAperiodicTaskFunction3, "APeriodic", configMINIMAL_STACK_SIZE, NULL, 4, NULL);
	xTaskCreate(vMainAperiodicTaskFunction4, "APeriodic", configMINIMAL_STACK_SIZE, NULL, 4, NULL);
	vTaskStartScheduler();
	while(1);
}
